theme: jekyll-theme-minimal
<img src="file:///Users/ginachaney/Downloads/PortfolioPortrait.png" alt="Portrait of me" height="200" width="100"/>
title: Gina Chaney
description: Junior Web Developer based outside of Houston, Texas.
